matrix:
- name: Markdown
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    encoding: utf-8
    wordlists:
    - .wordlist.txt
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      ignores:
      - code
      - pre
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: \\[\\**~]
      delimiters:
      # Ignore text between stars
      - open: '(?s)^(?P<open> **{3,})$'
        close: '(?P=open)'
  sources:
  - '**/*.md'
  default_encoding: utf-8
