name: Spellcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  PySpelling:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: GitHub Spellcheck Action 
      uses: rojopolis/spellcheck-github-actions@0.4.0
      
