name: Verify Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
      
    - name: Markdown Link Check
      uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
  
  spell-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: GitHub Spellcheck Action 
      uses: rojopolis/spellcheck-github-actions@0.5.0
      
