name: Verify Markdown Links

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
      
    - name: Markdown Link Check
      uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
